
# Aggregate Functions in Pandas | Ep-7 Pandas for detail

Aggregate functions are used to summarize data by computing a single value from multiple rows. Common aggregate functions in Pandas include:

- **sum()** - Calculate the sum of values
- **mean()** - Calculate the average
- **median()** - Calculate the middle value
- **std()** - Calculate standard deviation
- **min()** - Find minimum value
- **max()** - Find maximum value
- **count()** - Count non-null values
- **agg()** - Apply multiple functions at once

## Basic Usage

Use these functions directly on a DataFrame or Series to get summary statistics for your data.

## Groupby with Aggregation

Combine `groupby()` with aggregate functions to summarize data by categories and gain deeper insights into your dataset.

In [1]:
import pandas as pd
dos=(r"D:\\leanring\\aids\\learning\\pandes\\datasets\\iris.json")
df = pd.read_json(dos)
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             5.1          3.5           1.4          0.2     Setosa
2             4.9          3.0           1.4          0.2     Setosa
3             4.7          3.2           1.3          0.2     Setosa
4             4.6          3.1           1.5          0.2     Setosa
..            ...          ...           ...          ...        ...
146           6.7          3.0           5.2          2.3  Virginica
147           6.3          2.5           5.0          1.9  Virginica
148           6.5          3.0           5.2          2.0  Virginica
149           6.2          3.4           5.4          2.3  Virginica
150           5.9          3.0           5.1          1.8  Virginica

[151 rows x 5 columns]

In [2]:
print(df.mean(numeric_only=True))

sepal.length    5.838411
sepal.width     3.060265
petal.length    3.742384
petal.width     1.192715
dtype: float64

In [3]:
print(df.max(numeric_only=True))

sepal.length    7.9
sepal.width     4.4
petal.length    6.9
petal.width     2.5
dtype: float64

In [4]:
print(df.min(numeric_only=True))

sepal.length    4.3
sepal.width     2.0
petal.length    1.0
petal.width     0.1
dtype: float64

In [5]:
print(df.median(numeric_only=True))

sepal.length    5.8
sepal.width     3.0
petal.length    4.3
petal.width     1.3
dtype: float64

In [6]:
print(df['petal.length'].mean()) 
print(df['petal.length'].max())
print(df['petal.length'].min())

3.7423841059602645
6.9
1.0

In [7]:

print(df['petal.length'].sum())

565.0999999999999

In [8]:

group=df.groupby('variety')
print(group)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000019E26289E80>

In [9]:
print(group.mean(numeric_only=True))

            sepal.length  sepal.width  petal.length  petal.width
variety
Setosa          5.007843     3.429412      1.460784     0.245098
Versicolor      5.936000     2.770000      4.260000     1.326000
Virginica       6.588000     2.974000      5.552000     2.026000

# Data Cleaning in Pandas | Ep-8 Pandas

Data cleaning helps make your dataset accurate, consistent, and ready for analysis.

## Common Data Cleaning Steps

- **Handle missing values** using `fillna()`, `dropna()`
- **Drop unnecessary columns** using `drop()`
- **Rename or standardize values** using `replace()`
- **Convert text format** (e.g., lowercase) using string methods
- **Fix data types** using `astype()`
- **Remove duplicate rows** using `drop_duplicates()`

## Workflow Used in This Notebook

- Loaded a second dataset (`iris2.json`)
- Dropped `sepal.length` to create `df1`
- Filled missing values in `sepal.width`
- Replaced category values in `variety` (`Setosa` → `Sta`, `Virginica` → `Vir`)
- Converted `variety` text to lowercase
- Converted `sepal.length` to integer type
- Removed duplicate records

## Why Cleaning Matters

Clean data improves:
- reliability of summary statistics
- grouping and aggregation results
- model performance and interpretation

In [10]:

ios=(r"D:\\leanring\\aids\\learning\\pandes\\datasets\\iris2.json")
df = pd.read_json(ios)
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          NaN           1.4          0.3     Setosa
1             5.1          NaN           1.4          0.2     Setosa
2             5.1          3.5           1.4          0.2     Setosa
3             5.1          3.5           1.4          0.2     Setosa
4             5.1          3.5           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
150           6.7          3.0           5.2          2.3  Virginica
151           6.3          2.5           5.0          1.9  Virginica
152           6.5          3.0           5.2          2.0  Virginica
153           6.2          3.4           5.4          2.3  Virginica
154           5.9          3.0           5.1          1.8  Virginica

[155 rows x 5 columns]

In [11]:
df1=df.drop(columns=['sepal.length'])
df1

     sepal.width  petal.length  petal.width    variety
0            NaN           1.4          0.3     Setosa
1            NaN           1.4          0.2     Setosa
2            3.5           1.4          0.2     Setosa
3            3.5           1.4          0.2     Setosa
4            3.5           1.4          0.2     Setosa
..           ...           ...          ...        ...
150          3.0           5.2          2.3  Virginica
151          2.5           5.0          1.9  Virginica
152          3.0           5.2          2.0  Virginica
153          3.4           5.4          2.3  Virginica
154          3.0           5.1          1.8  Virginica

[155 rows x 4 columns]

In [12]:
df.fillna({"sepal.width": 3.0, "Sepal.Width": 4.0}, inplace=True)

In [13]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.0           1.4          0.3     Setosa
1             5.1          3.0           1.4          0.2     Setosa
2             5.1          3.5           1.4          0.2     Setosa
3             5.1          3.5           1.4          0.2     Setosa
4             5.1          3.5           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
150           6.7          3.0           5.2          2.3  Virginica
151           6.3          2.5           5.0          1.9  Virginica
152           6.5          3.0           5.2          2.0  Virginica
153           6.2          3.4           5.4          2.3  Virginica
154           5.9          3.0           5.1          1.8  Virginica

[155 rows x 5 columns]

In [14]:
df["variety"]=df["variety"].replace({"Setosa":"Sta", "Virginica":"Vir"})
print(df)

     sepal.length  sepal.width  petal.length  petal.width variety
0             5.1          3.0           1.4          0.3     Sta
1             5.1          3.0           1.4          0.2     Sta
2             5.1          3.5           1.4          0.2     Sta
3             5.1          3.5           1.4          0.2     Sta
4             5.1          3.5           1.4          0.2     Sta
..            ...          ...           ...          ...     ...
150           6.7          3.0           5.2          2.3     Vir
151           6.3          2.5           5.0          1.9     Vir
152           6.5          3.0           5.2          2.0     Vir
153           6.2          3.4           5.4          2.3     Vir
154           5.9          3.0           5.1          1.8     Vir

[155 rows x 5 columns]

In [15]:
df["variety"]=df["variety"].str.lower()
print(df)

     sepal.length  sepal.width  petal.length  petal.width variety
0             5.1          3.0           1.4          0.3     sta
1             5.1          3.0           1.4          0.2     sta
2             5.1          3.5           1.4          0.2     sta
3             5.1          3.5           1.4          0.2     sta
4             5.1          3.5           1.4          0.2     sta
..            ...          ...           ...          ...     ...
150           6.7          3.0           5.2          2.3     vir
151           6.3          2.5           5.0          1.9     vir
152           6.5          3.0           5.2          2.0     vir
153           6.2          3.4           5.4          2.3     vir
154           5.9          3.0           5.1          1.8     vir

[155 rows x 5 columns]

In [16]:
import numpy as np
df["sepal.length"]=df["sepal.length"].astype(np.int64)
print(df)

     sepal.length  sepal.width  petal.length  petal.width variety
0               5          3.0           1.4          0.3     sta
1               5          3.0           1.4          0.2     sta
2               5          3.5           1.4          0.2     sta
3               5          3.5           1.4          0.2     sta
4               5          3.5           1.4          0.2     sta
..            ...          ...           ...          ...     ...
150             6          3.0           5.2          2.3     vir
151             6          2.5           5.0          1.9     vir
152             6          3.0           5.2          2.0     vir
153             6          3.4           5.4          2.3     vir
154             5          3.0           5.1          1.8     vir

[155 rows x 5 columns]

In [17]:
df =df.drop_duplicates()
print(df)

     sepal.length  sepal.width  petal.length  petal.width variety
0               5          3.0           1.4          0.3     sta
1               5          3.0           1.4          0.2     sta
2               5          3.5           1.4          0.2     sta
6               4          3.0           1.4          0.2     sta
7               4          3.2           1.3          0.2     sta
..            ...          ...           ...          ...     ...
150             6          3.0           5.2          2.3     vir
151             6          2.5           5.0          1.9     vir
152             6          3.0           5.2          2.0     vir
153             6          3.4           5.4          2.3     vir
154             5          3.0           5.1          1.8     vir

[145 rows x 5 columns]