In [1]:
import pandas as pd
cos = (r"D:\\leanring\\aids\\learning\\pandes\\datasets\\customers-100.csv")
df = pd.read_csv(cos)
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [2]:
dos=(r"D:\\leanring\\aids\\learning\\pandes\\datasets\\iris.json")
df = pd.read_json(dos)
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [3]:
if 'cut' in df.columns:
    print(df[['cut']])
else:
    print("Column 'cut' not found.")
    print("Available columns:", df.columns.tolist())

Column 'cut' not found.
Available columns: ['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety']

## Selection in Pandas | Ep-5 Pandas

### Overview
Selection in Pandas is used to access specific rows, columns, or subsets of a DataFrame or Series. It helps you inspect and work with only the data you need.

### Key Concepts Covered

**Column Selection**
- Select a single column with `df["column"]`
- Select multiple columns with `df[["col1", "col2"]]`

**Row Selection**
- Use `.loc[]` to select rows by label
- Use `.iloc[]` to select rows by integer position

**Series Selection**
- A single column returns a Series
- Example: `city = df["City"]`

**Common Selection Methods**
- `df.head()` → first few rows
- `df.loc[row_label]` → row by label
- `df.iloc[row_index]` → row by position
- `df.iloc[row_start:row_end]` → slice rows

### Practical Examples
- `df["City"]` → selects the City column
- `df[['Customer Id', 'City', 'First Name', 'Last Name']]` → selects specific columns
- `df.loc[5]` → selects row with label 5
- `df.iloc[5]` → selects the 6th row
- `df.iloc[0:5, 0:3]` → selects first 5 rows and first 3 columns

### Notes
- Use `.loc[]` when working with index labels
- Use `.iloc[]` when working with row and column positions
- Selection is a core skill for filtering, cleaning, and analyzing data

In [4]:
cosr = (r"D:\leanring\aids\learning\pandes\datasets\customers-1000.csv")
df = pd.read_csv(cosr)
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/

In [5]:
city = df["City"]
city

0               Rowlandberg
1                  Bethside
2              Moniquemouth
3                Leeborough
4          Port Jacksonland
               ...
995       Lake Jacksonmouth
996    South Dominiquemouth
997         East Chloeshire
998             South Shane
999              East Wendy
Name: City, Length: 1000, dtype: object

In [6]:
print(df[['Customer Id', 'City', 'First Name', 'Last Name']])

         Customer Id                  City First Name Last Name
0    dE014d010c7ab0c           Rowlandberg     Andrew   Goodman
1    2B54172c8b65eC3              Bethside      Alvin      Lane
2    d794Dd48988d2ac          Moniquemouth      Jenna   Harding
3    3b3Aa4aCc68f3Be            Leeborough   Fernando      Ford
4    D60df62ad2ae41E      Port Jacksonland       Kara     Woods
..               ...                   ...        ...       ...
995  FbcCaF483aFaFAE     Lake Jacksonmouth      Diana    Monroe
996  979c4D58Ae9a9cc  South Dominiquemouth      Jerry   Morales
997  D0DcF6a4BcefCc8       East Chloeshire     Tracie     Floyd
998  90EE9CbbDa374E9           South Shane       Paul    Barnes
999  51732B5b2328015            East Wendy    Dominic     Duran

[1000 rows x 4 columns]

In [7]:
print(df.loc[5])

Index                                       6
Customer Id                   8aaa5d0CE9ee311
First Name                            Marissa
Last Name                              Gamble
Company                       Cherry and Sons
City                                Webertown
Country                                 Sudan
Phone 1                 001-645-334-5514x0786
Phone 2                         (751)980-3163
Email                katieallison@leonard.com
Subscription Date                  2021-11-17
Website               http://www.kaufman.org/
Name: 5, dtype: object

In [8]:
if 'Index' in df.columns:
    df = df.drop(columns=['Index'])
df = df.set_index('Customer Id')
df.head()

,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
Customer Id,,,,,,,,,,
dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/

In [9]:
print(df.loc["2B54172c8b65eC3"]) # loc is used to access a group of rows and columns by labels

First Name                                 Alvin
Last Name                                   Lane
Company              Terry, Proctor and Lawrence
City                                    Bethside
Country                         Papua New Guinea
Phone 1                       124-597-8652x05682
Phone 2                        321.441.0588x6218
Email                      alexandra86@mccoy.com
Subscription Date                     2021-06-24
Website                http://www.pena-cole.com/
Name: 2B54172c8b65eC3, dtype: object

In [10]:
print(df.iloc[5]) # iloc is used to access a group of rows and columns by integer position

First Name                            Marissa
Last Name                              Gamble
Company                       Cherry and Sons
City                                Webertown
Country                                 Sudan
Phone 1                 001-645-334-5514x0786
Phone 2                         (751)980-3163
Email                katieallison@leonard.com
Subscription Date                  2021-11-17
Website               http://www.kaufman.org/
Name: 8aaa5d0CE9ee311, dtype: object

In [11]:
print(df.iloc[0:5, 0:3]) # iloc is used to access a group of rows and columns by integer position, here we are accessing the first 5 rows and the first 3 columns

                First Name Last Name                      Company
Customer Id
dE014d010c7ab0c     Andrew   Goodman                Stewart-Flynn
2B54172c8b65eC3      Alvin      Lane  Terry, Proctor and Lawrence
d794Dd48988d2ac      Jenna   Harding                 Bailey Group
3b3Aa4aCc68f3Be   Fernando      Ford                 Moss-Maxwell
D60df62ad2ae41E       Kara     Woods              Mccarthy-Kelley

In [12]:
# iloc is used to access a group of rows and columns by integer position, here we are accessing the first 5 rows with a step of 2 and the first 3 columns
print(df.iloc[0:5:2, 0:3])

                First Name Last Name          Company
Customer Id
dE014d010c7ab0c     Andrew   Goodman    Stewart-Flynn
d794Dd48988d2ac      Jenna   Harding     Bailey Group
D60df62ad2ae41E       Kara     Woods  Mccarthy-Kelley

## Filtering in Pandas | Episode 6

### Overview
Filtering is a fundamental technique in data analysis that allows you to subset your data based on specific conditions. In this episode, we explored various methods to filter Pandas DataFrames using boolean indexing and comparison operators.

### Key Concepts Covered

**Boolean Indexing**
- Filter rows where a condition is True
- Returns only the rows that match your criteria
- Syntax: `df[df["column"] condition]`

**Comparison Operators**
- `>` Greater than
- `<` Less than
- `==` Equal to
- `!=` Not equal to
- `<=` Less than or equal to
- `>=` Greater than or equal to

**Combining Multiple Conditions**
- Use `&` (AND) to combine conditions: both must be True
- Use `|` (OR) to combine conditions: at least one must be True
- Use `~` (NOT) to negate a condition
- Always wrap each condition in parentheses

### Practical Examples from the Iris Dataset

1. **Single Condition (Greater Than)**
    - `df[df["sepal.length"] > 5.0]` → 118 rows with sepal length greater than 5.0

2. **Single Condition (Less Than or Equal)**
    - `df[df["sepal.length"] <= 5.0]` → 32 rows with sepal length ≤ 5.0

3. **Equality Filter**
    - `df[df['variety'] == "Setosa"]` → 50 Setosa flowers

4. **Inequality Filter**
    - `df[df['variety'] != "Setosa"]` → 100 non-Setosa flowers (Versicolor and Virginica)

5. **Multiple Conditions (AND)**
    - `df[(df['variety'] == "Setosa") & (df['petal.length'] <= 5.0)]` → 50 Setosa flowers with petal length ≤ 5.0

### Best Practices
- Always use parentheses around each condition when combining with `&` or `|`
- Check your data with `.head()` or `.info()` before filtering
- Use `!=` for "not equal to" comparisons
- Use `~` with parentheses for negating entire conditions: `df[~(df["variety"] == "Setosa")]`

In [13]:
df=pd.read_json("D:\leanring\\aids\learning\pandes\datasets\iris.json")
df.head(20)

    sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa

In [14]:
filtered1=df[df["sepal.length"] > 5.0]
print(filtered1)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
5             5.4          3.9           1.7          0.4     Setosa
10            5.4          3.7           1.5          0.2     Setosa
14            5.8          4.0           1.2          0.2     Setosa
15            5.7          4.4           1.5          0.4     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[118 rows x 5 columns]

In [15]:
filtered2=df[df["sepal.length"] <= 5.0]
print(filtered2)

     sepal.length  sepal.width  petal.length  petal.width     variety
1             4.9          3.0           1.4          0.2      Setosa
2             4.7          3.2           1.3          0.2      Setosa
3             4.6          3.1           1.5          0.2      Setosa
4             5.0          3.6           1.4          0.2      Setosa
6             4.6          3.4           1.4          0.3      Setosa
7             5.0          3.4           1.5          0.2      Setosa
8             4.4          2.9           1.4          0.2      Setosa
9             4.9          3.1           1.5          0.1      Setosa
11            4.8          3.4           1.6          0.2      Setosa
12            4.8          3.0           1.4          0.1      Setosa
13            4.3          3.0           1.1          0.1      Setosa
22            4.6          3.6           1.0          0.2      Setosa
24            4.8          3.4           1.9          0.2      Setosa
25            5.0          3.0           1.6          0.2      Setosa
26            5.0          3.4           1.6          0.4      Setosa
29            4.7          3.2           1.6          0.2      Setosa
30            4.8          3.1           1.6          0.2      Setosa
34            4.9          3.1           1.5          0.2      Setosa
35            5.0          3.2           1.2          0.2      Setosa
37            4.9          3.6           1.4          0.1      Setosa
38            4.4          3.0           1.3          0.2      Setosa
40            5.0          3.5           1.3          0.3      Setosa
41            4.5          2.3           1.3          0.3      Setosa
42            4.4          3.2           1.3          0.2      Setosa
43            5.0          3.5           1.6          0.6      Setosa
45            4.8          3.0           1.4          0.3      Setosa
47            4.6          3.2           1.4          0.2      Setosa
49            5.0          3.3           1.4          0.2      Setosa
57            4.9          2.4           3.3          1.0  Versicolor
60            5.0          2.0           3.5          1.0  Versicolor
93            5.0          2.3           3.3          1.0  Versicolor
106           4.9          2.5           4.5          1.7   Virginica

In [16]:
filtered3 = df[df['variety'] == "Setosa"]
print(filtered3)

    sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa
20           5.4          3.4           1.7          0.2  Setosa
21           5.1          3.7           1.5          0.4  Setosa
22           4.6          3.6           1.0          0.2  Setosa
23           5.1          3.3           1.7          0.5  Setosa
24           4.8          3.4           1.9          0.2  Setosa
25           5.0          3.0           1.6          0.2  Setosa
26           5.0          3.4           1.6          0.4  Setosa
27           5.2          3.5           1.5          0.2  Setosa
28           5.2          3.4           1.4          0.2  Setosa
29           4.7          3.2           1.6          0.2  Setosa
30           4.8          3.1           1.6          0.2  Setosa
31           5.4          3.4           1.5          0.4  Setosa
32           5.2          4.1           1.5          0.1  Setosa
33           5.5          4.2           1.4          0.2  Setosa
34           4.9          3.1           1.5          0.2  Setosa
35           5.0          3.2           1.2          0.2  Setosa
36           5.5          3.5           1.3          0.2  Setosa
37           4.9          3.6           1.4          0.1  Setosa
38           4.4          3.0           1.3          0.2  Setosa
39           5.1          3.4           1.5          0.2  Setosa
40           5.0          3.5           1.3          0.3  Setosa
41           4.5          2.3           1.3          0.3  Setosa
42           4.4          3.2           1.3          0.2  Setosa
43           5.0          3.5           1.6          0.6  Setosa
44           5.1          3.8           1.9          0.4  Setosa
45           4.8          3.0           1.4          0.3  Setosa
46           5.1          3.8           1.6          0.2  Setosa
47           4.6          3.2           1.4          0.2  Setosa
48           5.3          3.7           1.5          0.2  Setosa
49           5.0          3.3           1.4          0.2  Setosa

In [17]:
filtered3 = df[df['variety'] != "Setosa"]
print(filtered3)

     sepal.length  sepal.width  petal.length  petal.width     variety
50            7.0          3.2           4.7          1.4  Versicolor
51            6.4          3.2           4.5          1.5  Versicolor
52            6.9          3.1           4.9          1.5  Versicolor
53            5.5          2.3           4.0          1.3  Versicolor
54            6.5          2.8           4.6          1.5  Versicolor
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3   Virginica
146           6.3          2.5           5.0          1.9   Virginica
147           6.5          3.0           5.2          2.0   Virginica
148           6.2          3.4           5.4          2.3   Virginica
149           5.9          3.0           5.1          1.8   Virginica

[100 rows x 5 columns]

In [18]:
filtered4 = df[(df['variety'] == "Setosa") & (df['petal.length'] <= 5.0)]
print(filtered4)

    sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa
20           5.4          3.4           1.7          0.2  Setosa
21           5.1          3.7           1.5          0.4  Setosa
22           4.6          3.6           1.0          0.2  Setosa
23           5.1          3.3           1.7          0.5  Setosa
24           4.8          3.4           1.9          0.2  Setosa
25           5.0          3.0           1.6          0.2  Setosa
26           5.0          3.4           1.6          0.4  Setosa
27           5.2          3.5           1.5          0.2  Setosa
28           5.2          3.4           1.4          0.2  Setosa
29           4.7          3.2           1.6          0.2  Setosa
30           4.8          3.1           1.6          0.2  Setosa
31           5.4          3.4           1.5          0.4  Setosa
32           5.2          4.1           1.5          0.1  Setosa
33           5.5          4.2           1.4          0.2  Setosa
34           4.9          3.1           1.5          0.2  Setosa
35           5.0          3.2           1.2          0.2  Setosa
36           5.5          3.5           1.3          0.2  Setosa
37           4.9          3.6           1.4          0.1  Setosa
38           4.4          3.0           1.3          0.2  Setosa
39           5.1          3.4           1.5          0.2  Setosa
40           5.0          3.5           1.3          0.3  Setosa
41           4.5          2.3           1.3          0.3  Setosa
42           4.4          3.2           1.3          0.2  Setosa
43           5.0          3.5           1.6          0.6  Setosa
44           5.1          3.8           1.9          0.4  Setosa
45           4.8          3.0           1.4          0.3  Setosa
46           5.1          3.8           1.6          0.2  Setosa
47           4.6          3.2           1.4          0.2  Setosa
48           5.3          3.7           1.5          0.2  Setosa
49           5.0          3.3           1.4          0.2  Setosa